"""Auto-wrapped Modal harness for modal_hupd_bert_train.py.

Generated by gpu2modal autowrap on 2026-09-02T11:09:44.
Re-runs the user's plain Python script inside a Modal container.

Usage:
    modal run modal_modal_hupd_bert_train.py
"""
from __future__ import annotations
import subprocess, sys, time
from pathlib import Path
import modal

HERE = Path(__file__).parent.resolve()
RESULTS = HERE / "results"
RESULTS.mkdir(exist_ok=True)

image = (
    modal.Image.debian_slim(python_version="3.11")
    .pip_install("torch", "transformers", "scikit-learn")
    .add_local_file("E:/Projects/Submitted/311/modal_hupd_bert_train.py", "/app/script.py")
    .add_local_file("E:/Projects/Submitted/311/results/hupd_split.json", "/app/hupd_split.json")
)

app = modal.App("autowrap-modal-hupd-bert-train", image=image)
results_vol = modal.Volume.from_name("autowrap-modal-hupd-bert-train-results", create_if_missing=True)


@app.function(
    gpu="A10G",
    timeout=3600,
    memory=8192,
    cpu=2.0,
    volumes={"/results": results_vol},
)
def run_script() -> dict:
    import os, sys
    os.chdir("/app")
    t0 = time.time()
    print(f"[autowrap] starting modal_hupd_bert_train.py", flush=True)
    import torch
    if torch.cuda.is_available():
        print(f"[autowrap] GPU: {torch.cuda.get_device_name(0)}", flush=True)
    else:
        print("[autowrap] WARN no CUDA in container", flush=True)
    cmd = ["python", "-u", "/app/script.py"] + []
    print(f"[autowrap] $ {' '.join(cmd)}", flush=True)
    rc = subprocess.call(cmd, cwd="/app")
    elapsed = time.time() - t0
    print(f"[autowrap] script exit rc={rc} elapsed={elapsed:.1f}s", flush=True)

    # Persist any files the script wrote under /app/results/ to the volume
    src = Path("/app/results")
    if src.exists():
        import shutil
        for p in src.rglob("*"):
            if p.is_file():
                rel = p.relative_to(src)
                dst = Path("/results") / rel
                dst.parent.mkdir(parents=True, exist_ok=True)
                shutil.copy2(p, dst)
        results_vol.commit()
        print(f"[autowrap] persisted results to volume", flush=True)

    print("[autowrap] === DONE ===", flush=True)
    return {"rc": rc, "elapsed_s": round(elapsed, 1)}


@app.local_entrypoint()
def main():
    result = run_script.remote()
    print(f"[local] remote returned: {result}", flush=True)
    # Download volume contents
    import subprocess as sp
    rc = sp.call(["modal", "volume", "get", "--force", "autowrap-modal-hupd-bert-train-results", "/", str(RESULTS)])
    print(f"[local] modal volume get rc={rc}; results -> {RESULTS}", flush=True)
